name: Run script

on: [push]

jobs:
  buildssconf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Execute Shell Script
      run: |
        cd script
        chmod +x script.sh
        ./script.sh
        pwd
        ls

    - name: Move Configuration File
      run: |
        mv -f script/lazy_group.conf conf/lazy_group.conf
