name: my_ss_conf

on:
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Run Shell Script
      run: |
        cd script/
        bash ssconf.sh
        mv -f lazy_group.conf /conf/lazy_group.conf
