name: my_ss_conf

on:
  schedule:
    - cron: '0 3 * * 3'  # 每周三的凌晨3点执行

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Run Shell Script
      run: |
        bash script/ssconf.sh
        mv -f script/lazy_group.conf conf/lazy_group.conf
