name: Run script

on: [push]

jobs:
  buildssconf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: bulid
      run: |
        cd script
        chmod +x script.sh
        ./script.sh
        mv lazy_group.conf ../conf/
    - name: Upload lazy_group.conf
      uses: actions/upload-artifact@v2
      with:
        name: lazy-group-config
        path: conf/lazy_group.conf
