name: My SS Conf Test

on:
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Run Shell Script
      run: |
        bash script/ssconf.sh
        mv -f lazy_group.conf ../lazy_group.conf
